M48
; DRILL file {KiCad 7.0.7} date Wed Sep 20 11:02:54 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-20T11:02:54-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1575
%
G90
G05
T1
X2.8843Y-7.5836
X2.8882Y-3.6466
X13.9118Y-3.6427
X13.9118Y-7.5836
T0
M30
